title: Mews Documentation
baseurl: /public

defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"
    -
        scope:
            path: "status"
        values:
            layout: "status"

markdown: kramdown

kramdown:
  input: GFM
  toc_levels: 1..3

gems:
    - jekyll-sitemap
